# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EKbana Study Group
email: anilkumar.shrestha@ekbana.info
description: > # this means to ignore newlines until "baseurl:"
  EKbana Study group page.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "https://github.com/anilkumarshrestha/ekbana-study-group/" # the base hostname & protocol for your site
twitter_username: ekbana
github_username:  ekbana
disqus_username:

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter: rouge
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"
# As Github pages updates it dependency Jekyll to 4.0 change catagories to slugified_categories
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
search_tag: '/tags'
